### ISSUE TITLE
Write a production deployment checklist

### ISSUE THREAD

**Issue by tapanih** [ohtu2021-kvantti/WebMark#150]
There are things that need to be done to make the application production-ready (performance and security-related). Document these steps.

Production deployment list is here: https://github.com/ohtu2021-kvantti/WebMark/wiki/Production-deployment-checklist

- [ ] Performance related checks
- [x] Security related checks
- [x] Other checks related to production deployment
